#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

# Numpy Exercise

#### 2. Print the numpy version and the configuration

In [3]:
print(np.__version__)

2.3.5


#### 3. Create a null vector of size 10

In [4]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [8]:
array = np.array([1,2,3,4,5])

print("Memory size of the array =", array.nbytes)

Memory size of the array =  40


#### 5.  How to get the documentation of the numpy add function from the command line?

In [9]:
import numpy as np
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [14]:
vector = np.zeros(10)
vector[4] = 1

print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [15]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [16]:
vector = np.arange(10, 20)

reversed_vector = vector[::-1]

print(reversed_vector)

[19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
matrix = np.arange(9).reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [18]:
arr = np.array([1, 2, 0, 0, 4, 0])

indices = np.nonzero(arr)

print(indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [19]:
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [20]:
array = np.random.random((3, 3, 3))

print(array)

[[[0.73527364 0.86969785 0.69292051]
  [0.73863751 0.33582686 0.87506834]
  [0.23635218 0.44778545 0.60982977]]

 [[0.52757709 0.16749209 0.13397906]
  [0.10692174 0.73992035 0.26773498]
  [0.33347204 0.96540576 0.922522  ]]

 [[0.05275317 0.89504501 0.70560008]
  [0.15921052 0.90623008 0.42271011]
  [0.0616222  0.93939225 0.1376918 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [21]:
array = np.random.random((10, 10))

min_value = array.min()
max_value = array.max()

print("Array:\n", array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)

Array:
 [[0.93405449 0.22146351 0.07992348 0.56541257 0.54315245 0.0288318
  0.52496233 0.37390783 0.79205962 0.38174511]
 [0.02663207 0.24351227 0.27265059 0.66728681 0.50930846 0.99222797
  0.36872551 0.87858432 0.74294755 0.62061285]
 [0.89544749 0.89024752 0.4476843  0.35814272 0.25198121 0.09728811
  0.06544272 0.94203698 0.99977056 0.44818998]
 [0.58214717 0.13275176 0.97347926 0.14805225 0.44728588 0.6382523
  0.96455657 0.94626498 0.06071095 0.65919736]
 [0.90997074 0.18195449 0.42631361 0.1528428  0.42269038 0.68918326
  0.90844323 0.59567415 0.48959966 0.32168131]
 [0.05872581 0.44648565 0.83818436 0.84942158 0.76542624 0.95691238
  0.87101184 0.50849323 0.98598793 0.7725705 ]
 [0.90973709 0.59124542 0.12876769 0.75514737 0.32961011 0.60130149
  0.1197234  0.76585749 0.97118662 0.34243267]
 [0.34374401 0.10365184 0.84330042 0.48917345 0.10991915 0.3813005
  0.35974581 0.52833673 0.42617456 0.01574637]
 [0.04961571 0.76702099 0.40097487 0.62148876 0.29191952 0.23237554
  0.437

#### 14. Create a random vector of size 30 and find the mean value

In [22]:
vector = np.random.random(30)

mean_value = vector.mean()

print("Random vector:\n", vector)
print("\nMean value:", mean_value)

Random vector:
 [0.65232381 0.66883398 0.39037368 0.52326789 0.6320844  0.72807082
 0.45623789 0.56245305 0.94896011 0.69134405 0.24886184 0.49041048
 0.93659512 0.49998777 0.18512845 0.51509447 0.09454126 0.5663784
 0.23778195 0.84979124 0.79777814 0.74182149 0.33057482 0.59561892
 0.01335394 0.43582386 0.39284435 0.08868837 0.13079683 0.63295082]

Mean value: 0.5012924074084862


#### 15. Create a 2d array with 1 on the border and 0 inside

In [23]:
array = np.ones((5, 5))

array[1:-1, 1:-1] = 0

print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [24]:
array = np.ones((3, 3))

new_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)

print(new_array)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan  
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [25]:
matrix = np.diag([1, 2, 3, 4], k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [26]:
matrix = np.zeros((8, 8), dtype=int)

matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [27]:
index = np.unravel_index(100, (6, 7, 8))
print(index)

(np.int64(1), np.int64(5), np.int64(4))
